In [1]:
#Colab資料夾設定方法
#!pip install google.colab #如未安裝取消註解後執行
import os

from google.colab import drive
drive.mount('/content/drive')

##出現提示欄進行授權

os.chdir('/content/drive/My Drive/newmovie/newdatas') #切換該目錄
# os.listdir() #確認目錄內容

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from itertools import permutations

In [3]:
ratings = pd.read_csv('ratings_t.csv')

# ratings = pd.read_csv('ratings_t.csv')
ratings

,userId,movieId,rating,tmdbId,imdbId,title
0,1,110,1.0,197.0,112573.0,Braveheart
1,1,147,4.5,10474.0,112461.0,The Basketball Diaries
2,1,858,5.0,238.0,68646.0,The Godfather
3,1,1221,5.0,240.0,71562.0,The Godfather: Part II
4,1,1246,5.0,207.0,97165.0,Dead Poets Society
...,...,...,...,...,...,...
25886770,270896,58559,5.0,155.0,468569.0,The Dark Knight
25886771,270896,60069,5.0,10681.0,910970.0,WALL·E
25886772,270896,63082,4.5,12405.0,1010048.0,Slumdog Millionaire
25886773,270896,64957,4.5,4922.0,421715.0,The Curious Case of Benjamin Button
25886774,270896,71878,2.0,19904.0,814335.0,The Stepfather

In [4]:
ratings = ratings.drop_duplicates(keep='last')

In [5]:
ratings

,userId,movieId,rating,tmdbId,imdbId,title
0,1,110,1.0,197.0,112573.0,Braveheart
1,1,147,4.5,10474.0,112461.0,The Basketball Diaries
2,1,858,5.0,238.0,68646.0,The Godfather
3,1,1221,5.0,240.0,71562.0,The Godfather: Part II
4,1,1246,5.0,207.0,97165.0,Dead Poets Society
...,...,...,...,...,...,...
25886770,270896,58559,5.0,155.0,468569.0,The Dark Knight
25886771,270896,60069,5.0,10681.0,910970.0,WALL·E
25886772,270896,63082,4.5,12405.0,1010048.0,Slumdog Millionaire
25886773,270896,64957,4.5,4922.0,421715.0,The Curious Case of Benjamin Button
25886774,270896,71878,2.0,19904.0,814335.0,The Stepfather

In [6]:
a = ratings.groupby('movieId')['rating'].count()
a.describe()

count    37960.000000
mean       679.700843
std       3297.624509
min          1.000000
25%          3.000000
50%         11.000000
75%        107.000000
max      91921.000000
Name: rating, dtype: float64

In [7]:
a

movieId
1         66008
2         26060
3         15497
4          2981
5         15258
          ...
176259        1
176263        1
176267        1
176271        1
176273        1
Name: rating, Length: 37960, dtype: int64

In [8]:
lessviewmovie = a[a<10].index
lessviewmovie

Int64Index([  1781,   1847,   2277,   2958,   3195,   3290,   3312,   3356,
              3381,   3411,
            ...
            176235, 176249, 176251, 176255, 176257, 176259, 176263, 176267,
            176271, 176273],
           dtype='int64', name='movieId', length=18115)

In [9]:
ratings = ratings[~ratings['movieId'].isin(lessviewmovie)]
ratings

,userId,movieId,rating,tmdbId,imdbId,title
0,1,110,1.0,197.0,112573.0,Braveheart
1,1,147,4.5,10474.0,112461.0,The Basketball Diaries
2,1,858,5.0,238.0,68646.0,The Godfather
3,1,1221,5.0,240.0,71562.0,The Godfather: Part II
4,1,1246,5.0,207.0,97165.0,Dead Poets Society
...,...,...,...,...,...,...
25886770,270896,58559,5.0,155.0,468569.0,The Dark Knight
25886771,270896,60069,5.0,10681.0,910970.0,WALL·E
25886772,270896,63082,4.5,12405.0,1010048.0,Slumdog Millionaire
25886773,270896,64957,4.5,4922.0,421715.0,The Curious Case of Benjamin Button
25886774,270896,71878,2.0,19904.0,814335.0,The Stepfather

In [10]:
r = ratings.groupby('userId')['rating'].count()

In [11]:
r

userId
1          27
2          22
3          10
4          62
5          26
         ...
270892     75
270893    190
270894    143
270895     20
270896    258
Name: rating, Length: 270841, dtype: int64

In [12]:
r.describe()

count    270841.000000
mean         95.043387
std         199.282571
min           1.000000
25%          15.000000
50%          30.000000
75%          92.000000
max       10971.000000
Name: rating, dtype: float64

In [21]:
# r[r<100]
r = r[(r>43) & (r<54)]
userfilter = r.index
r

userId
7         53
33        47
77        45
80        45
97        49
          ..
270721    48
270726    51
270799    49
270832    46
270881    44
Name: rating, Length: 12904, dtype: int64

In [22]:
r.describe()

count    12904.000000
mean        48.397784
std          2.859482
min         44.000000
25%         46.000000
50%         48.000000
75%         51.000000
max         53.000000
Name: rating, dtype: float64

In [23]:
ratings = ratings[ratings['userId'].isin(userfilter)]
ratings

          userId  movieId  rating   tmdbId    imdbId                     title
151            7      293     5.0    101.0  110413.0    Leon: The Professional
152            7      318     4.0    278.0  111161.0  The Shawshank Redemption
153            7     2571     4.0    603.0  133093.0                The Matrix
154            7     2858     4.5     14.0  169547.0           American Beauty
155            7     2959     4.5    550.0  137523.0                Fight Club
...          ...      ...     ...      ...       ...                       ...
25883293  270881     6244     2.5  45129.0   96028.0            Salaam Bombay!
25883294  270881     6245     3.0  42618.0   65054.0             Sweet Charity
25883295  270881     6271     4.5   1675.0   70460.0             Day for Night
25883296  270881     6301     3.5    994.0   67800.0                Straw Dogs
25883297  270881     6305     3.5   1714.0   60390.0            Fahrenheit 451

[624525 rows x 6 columns]

In [25]:
ratings.to_csv("ratings_renew.csv",index=True)

In [32]:
# ratings = pd.read_csv('ratings_renew.csv', index_col=0)

        movieId  rating   tmdbId    imdbId                    title
userId
1            31     2.5   9909.0  112792.0          Dangerous Minds
1          1029     3.0  11360.0   33563.0                    Dumbo
1          1061     3.0    819.0  117665.0                 Sleepers
1          1129     2.0   1103.0   82340.0     Escape from New York
1          1172     4.0  11216.0   95765.0          Cinema Paradiso
...         ...     ...      ...       ...                      ...
671        6212     2.5  10678.0  305669.0  Bringing Down the House
671        6268     2.5  25461.0  316188.0    Raising Victor Vargas
671        6365     4.0    604.0  234215.0      The Matrix Reloaded
671        6385     2.5   1088.0  298228.0              Whale Rider
671        6565     3.5   4464.0  329575.0               Seabiscuit

[99392 rows x 5 columns]

In [33]:
ratings

,userId,movieId,rating,tmdbId,imdbId,title
0,1,110,1.0,197.0,112573.0,Braveheart
1,1,147,4.5,10474.0,112461.0,The Basketball Diaries
2,1,858,5.0,238.0,68646.0,The Godfather
3,1,1221,5.0,240.0,71562.0,The Godfather: Part II
4,1,1246,5.0,207.0,97165.0,Dead Poets Society
...,...,...,...,...,...,...
25886158,270892,27869,4.0,11658.0,386064.0,Tae Guk Gi: The Brotherhood of War
25886159,270892,44191,3.5,752.0,434409.0,V for Vendetta
25886160,270892,55118,4.0,2252.0,765443.0,Eastern Promises
25886161,270892,58191,3.5,13362.0,854678.0,Taxi to the Dark Side
25886162,270892,59731,4.0,13636.0,1151309.0,Bigger Stronger Faster*

In [11]:
ratings = ratings1.head(100000)

In [24]:



# Create the function to find all permutations
def find_movie_pairs(x):
  pairs = pd.DataFrame(list(permutations(x.values, 2)),
                       columns=['movie_a', 'movie_b'])
  return pairs

# Apply the function to the title column and reset the index
movie_combinations = ratings.groupby('userId')['title'].apply(find_movie_pairs).reset_index(drop=True)

# Calculate how often each item in movies_a occurs with the items in movies_b
combination_counts = movie_combinations.groupby(['movie_a', 'movie_b']).size()



# Convert the results to a DataFrame and reset the index
combination_counts_df = combination_counts.to_frame(name='size').reset_index()


# Sort the counts from highest to lowest
combination_counts_df.sort_values('size', ascending=False, inplace=True)

# Find the movies most frequently watched by people who watched Thor
Godfather_df = combination_counts_df[combination_counts_df['movie_a'] == 'The Godfather']



Godfather_df.head(10)

               movie_a                   movie_b  size
4233380  The Godfather  The Shawshank Redemption  1307
4232238  The Godfather                 Star Wars  1214
4232833  The Godfather    The Godfather: Part II  1135
4233113  The Godfather                The Matrix  1120
4231679  The Godfather              Pulp Fiction  1103
4231939  The Godfather          Schindler's List  1055
4229885  The Godfather                Fight Club  1010
4233386  The Godfather  The Silence of the Lambs   999
4233513  The Godfather        The Usual Suspects   898
4229955  The Godfather              Forrest Gump   891